# Generated by Django 4.1.4 on 2023-02-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('abrev', models.CharField(max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '_Facultad',
                'verbose_name_plural': '_Facultades',
                'db_table': 'clas_facultad',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FormaPosgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('abrev', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '_Forma de Posgrado',
                'verbose_name_plural': '_Formas de Posgrado',
                'db_table': 'clas_formaPosgrado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '_Organismo',
                'verbose_name_plural': '_Organismos',
                'db_table': 'clas_organismo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3)),
                ('area', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '_Pais',
                'verbose_name_plural': '_Paises',
                'db_table': 'clas_pais',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('rama', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': '_Programa',
                'verbose_name_plural': '_Programas',
                'db_table': 'clas_programa',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Posgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('modalidad', models.CharField(choices=[('TC', 'Tiempo Completo'), ('TP', 'Tiempo Parcial'), ('AD', 'A Distancia')], max_length=15)),
                ('cum', models.BooleanField(verbose_name='Ejecutado en CUM')),
                ('pais', models.BooleanField(verbose_name='Ejecutado en otro pais')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de terminación')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgrado.programa')),
                ('facultad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posgrado.facultad')),
                ('forma', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posgrado.formaposgrado', verbose_name='Forma de Posgrado')),
            ],
            options={
                'verbose_name': 'posgrado',
                'verbose_name_plural': 'posgrados',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('CI', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido1', models.CharField(max_length=50)),
                ('apellido2', models.CharField(max_length=50)),
                ('pasaporte', models.CharField(max_length=20, null=True)),
                ('sexo', models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], max_length=10, verbose_name='Sexo')),
                ('domicilio', models.CharField(default='No definido', max_length=150)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('correo', models.EmailField(max_length=50, null=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgrado.pais', verbose_name='País')),
            ],
            options={
                'verbose_name': 'persona',
                'verbose_name_plural': 'personas',
                'ordering': ['apellido1'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduado', models.BooleanField(default=False)),
                ('organismo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgrado.organismo')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgrado.persona')),
                ('posgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgrado.posgrado')),
            ],
            options={
                'verbose_name': 'matricula',
                'verbose_name_plural': 'matriculas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emitido', models.CharField(max_length=150)),
                ('firmado', models.CharField(max_length=150)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgrado.persona')),
                ('posgrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgrado.posgrado')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
            },
        ),
    ]
