# Generated by Django 4.1.4 on 2023-01-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgrado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPosgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('abrev', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Forma de Posgrado',
                'verbose_name_plural': 'Formas de Posgrado',
                'db_table': 'clas_formaPosgrado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('sigla', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Organismo',
                'verbose_name_plural': 'Organismos',
                'db_table': 'clas_organismo',
                'ordering': ['id'],
            },
        ),
    ]
