# Generated by Django 4.1.4 on 2023-03-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgrado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='evaluacion',
            field=models.IntegerField(choices=[(0, 'No evaluado'), (2, 'Mal'), (3, 'Regular'), (4, 'Bien'), (5, 'Excelente')], default=0, verbose_name='Evaluación'),
        ),
    ]
