# Generated by Django 4.1.4 on 2023-01-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgrado', '0002_formaposgrado_organismo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3)),
                ('area', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'db_table': 'clas_pais',
                'ordering': ['id'],
            },
        ),
    ]
