# Generated by Django 4.1.4 on 2023-03-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgrado', '0002_matricula_evaluacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='posgrado',
            name='edicion',
            field=models.IntegerField(default=1, verbose_name='Edición'),
        ),
    ]
