# Generated by Django 4.1.4 on 2023-01-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posgrado', '0003_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('rama', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'programa',
                'verbose_name_plural': 'programas',
                'db_table': 'clas_programa',
                'ordering': ['codigo'],
            },
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
    ]
