# Generated by Django 4.1.4 on 2023-01-26 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgrado', '0004_programa_alter_pais_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posgrado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('edicion', models.PositiveIntegerField(default=1)),
                ('modalidad', models.CharField(choices=[('TC', 'Tiempo Completo'), ('TP', 'Tiempo Parcial'), ('AD', 'A Distancia')], max_length=15)),
                ('cum', models.BooleanField(verbose_name='Ejecutado en CUM')),
                ('pais', models.BooleanField(verbose_name='Ejecutado en otro pais')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posgrado.programa')),
                ('facultad', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posgrado.facultad')),
                ('forma', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='posgrado.formaposgrado', verbose_name='Forma de Posgrado')),
            ],
            options={
                'verbose_name': 'posgrado',
                'verbose_name_plural': 'posgrados',
                'ordering': ['nombre'],
            },
        ),
    ]
