# Generated by Django 4.1.5 on 2023-01-26 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgrado', '0006_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='posgrado',
            name='fecha_fin',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='posgrado',
            name='fecha_inicio',
            field=models.DateField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graduado', models.BooleanField(default=False)),
                ('facultad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posgrado.facultad')),
                ('organismo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posgrado.organismo')),
                ('pais', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posgrado.pais')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posgrado.persona')),
                ('posgrado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posgrado.posgrado')),
            ],
            options={
                'verbose_name': 'matricula',
                'verbose_name_plural': 'matriculas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emitido', models.CharField(max_length=150)),
                ('firmado', models.CharField(max_length=150)),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posgrado.persona')),
                ('posgrado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posgrado.posgrado')),
            ],
            options={
                'verbose_name': 'certificado',
                'verbose_name_plural': 'certificados',
            },
        ),
    ]
