# Generated by Django 4.1.4 on 2023-01-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posgrado', '0007_posgrado_fecha_fin_posgrado_fecha_inicio_matricula_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultad',
            options={'ordering': ['id'], 'verbose_name': '_Facultad', 'verbose_name_plural': '_Facultades'},
        ),
        migrations.AlterModelOptions(
            name='formaposgrado',
            options={'ordering': ['id'], 'verbose_name': '_Forma de Posgrado', 'verbose_name_plural': '_Formas de Posgrado'},
        ),
        migrations.AlterModelOptions(
            name='organismo',
            options={'ordering': ['id'], 'verbose_name': '_Organismo', 'verbose_name_plural': '_Organismos'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['nombre'], 'verbose_name': '_Pais', 'verbose_name_plural': '_Paises'},
        ),
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['codigo'], 'verbose_name': '_Programa', 'verbose_name_plural': '_Programas'},
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='facultad',
        ),
        migrations.RemoveField(
            model_name='posgrado',
            name='edicion',
        ),
    ]
