# Generated by Django 4.1.4 on 2023-01-31 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posgrado', '0008_alter_facultad_options_alter_formaposgrado_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='pais',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posgrado.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='posgrado',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha de terminación'),
        ),
        migrations.AlterField(
            model_name='posgrado',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
    ]
