# Generated by Django 4.1.5 on 2023-03-07 17:10

from django.db import migrations, models
import solapin.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolapinPersona',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('area_general', models.CharField(max_length=255)),
                ('area_trabajo', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=solapin.models.user_directory_path)),
                ('libre_acceso', models.BooleanField(default=False)),
                ('diseno_superior', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'solapin_persona',
            },
        ),
    ]
